#### [word,     cty_low, cty_mid, cty_high] 
#### a simple find word matches against the text of a transactions descripotion
#### It is then used to categorise the transactions - lowest, middle highest abstraction

__matchers__ = [

['goldex',                                      'costa', 'soho', 'luxury'],
['storage king',                                'storage', 'utilities', 'utilities'],
['storageking',                                 'storage', 'utilities', 'utilities'],
['nexgen',                                      'internet', 'utilities', 'utilities'],
['smith and webb',                              'kitchen', 'homeware', 'house'],
['tomtom',                                      'gadgets', 'car', 'travel'],
['sains',                                       'sainsburys', '-', 'groceries'],
['waitrose',                                    'waitrose', '-', 'groceries'],
['asda',                                        'asda', '-', 'groceries'],
['tesco',                                       'tesco', '-', 'groceries'],
['ocado',                                       'ocado', '-', 'groceries'],
['the swan',                                    'eat out', 'eat out', 'entertainment'],
['thai moom',                                   'eat out', 'eat out', 'entertainment'],
['scared crow',                                 'eat out', 'eat out', 'entertainment'],
['dominos pizza',                               'eat in', '-', 'eat in'],
['sino',                                        'eat out', 'eat out', 'entertainment'],
['Esso Moto',                                   'eat out', 'eat out', 'entertainment'],
['Gufaaraja',                                   'eat out', 'eat out', 'entertainment'],
['The Hengist AYLESFORD',                       'eat out', 'eat out', 'entertainment'],
['Woods Restaurant Ltd',                        'eat out', 'eat out', 'entertainment'],
['Dhaka Tandoori',                              'eat out', 'eat out', 'entertainment'],
['Id West Malling Ltd',                         'eat out', 'eat out', 'entertainment'],
['Welcome Break',                               'eat out', 'eat out', 'entertainment'],
['packing ware',                                'ebay', '-', 'ebay'],
['tonbridge and mall',                          'council tax', 'utilities', 'utilities'],
['TONBRIDGE & MALL',                            'council tax', 'utilities', 'utilities'],
['southern water',                              'water', 'utilities', 'utilities'],
['sky digital',                                 'sky ', 'utilities', 'utilities'],
['south east water',                            'water', 'utilities', 'utilities'],
['tv licence',                                  'tv', 'utilities', 'utilities'],
['gas',                                         'british gas', 'utilities', 'utilities'],
['bt group',                                    'phone', 'utilities', 'utilities'],
['O2',                                    'phone', 'utilities', 'utilities'],
['Carphone Warehouse',                                    'phone', 'utilities', 'utilities'],    
['MID KENT WATER LTD',                          'water', 'utilities', 'utilities'],
['simplyhealth',                                'health', 'insurance', 'insurance'],
    
['david lloyd',                                 'gym', 'gym', 'health'],
['Kings Hill dental',                                 'dental', 'dental', 'health'],
['bmihealth',                                 'dental', 'dental', 'health'],
['SAntander mortgage',                          'mortgage', 'mortgage', 'mortgage'],
['pinn insu',                                   'insurance', '-', 'insurance'],
['PINNACLE INSURANCE',                          'insurance', '-', 'insurance'],
['premium credit',                              'insurance', '-', 'insurance'],
['scottish provident',                          'insurance', '-', 'insurance'],
['direct line',                                 'insurance', '-', 'insurance'],
['legal & gen mi',                              'insurance', '-', 'insurance'],
['aviva',                                       'insurance', '-', 'insurance'],
['L&G ASSCE SOC LTD',                           'insurance', '-', 'insurance'],
['Abbotsley Veterinary',                        'vet', '-', 'insurance'],
['0664/640 693 584',                            'transfer', '-', 'transfer'],
['0572/632 896 821',                            'transfer', '-', 'transfer'],
['paul brian',                                  'transfer', '-', 'transfer'],
['barclaycard',                            'transfer', '-', 'transfer'],
['hsbc card services',                          'transfer', '-', 'transfer'],
['NATIONWIDE C/CARD',                           'transfer', '-', 'transfer'],    
['hsbc bank plc',                               'transfer', '-', 'transfer'],
['0220/648 872 431',                            'transfer', '-', 'transfer'],
['07-00-40',                                    'transfer', '-', 'transfer'],
['MIKADO SOFTW',                                'transfer', '-', 'transfer'],
['AMAZON.CO.UK',                                'books', 'books', 'house'],
['ITUNES.COM',                                  'itunes', 'books', 'house'],
['Autoglass',                                   'windscreen', 'car', 'travel'],
['BP Parkfoot S/Stn',                           'fuel', 'car', 'travel'],
['BP Three Elm S/Stn',                          'fuel', 'car', 'travel'],
['BT DIRECT DEBITS',                            'bt', 'utilities', 'utilities'],
['Cash machine',                                'cash', 'cash', 'cash'],
['Cash withdraw',                               'cash', 'cash', 'cash'],
['Cheque:',                                     'cheque', 'cheque', 'chequeout'],
['Clacket Lane Serv',                           'fuel', 'car', 'travel'],
['Down Swan Street',                            'gifts', 'gifts', 'gifts'],
['Cath Kidston',                            'gifts', 'clothes', 'clothes'],    
['Kings Hill Pharmac',                          'medicince', 'medicine', 'medicine'],
['WWW.Johnlewis.Com',                           'homeware', 'homeware', 'house'],
['51*Jcrew Purchase 877-315-4709',              '-', '-', 'clothes'],
['Aldi Stores',                                 'aldi', '-', 'groceries'],
['Ape Concessions WAREHAM',                     'monkeyworld', '-', 'entertainment'],
['Avis Maidstone E333046766',                   '-', '-', 'mikadoexpenses'],
['B & Q',                                       '-', 'diy', 'house'],
['Bailey Wighton Ltd',                          'bathroomflooring', 'diy', 'house'],
['Boots BLUEWATER',                             'pharamcy', '-', 'health'],
['Brands Hatch',                                'olympics', '-', 'entertainment'],
['Cheque credit',                               '-', '-', 'paidin'],
['Co-Op Group',                                 '-', '-', 'groceries'],
['David & Goliath',                             '-', '-', 'gifts'],
['Enterprise 01622 663656',                     '-', 'carhire', 'travel'],
['Google *Appspremier GOOGLE.COM/CH',           '-', '-', 'mikadoexpenses'],
['HSA',                                         '-', '-', 'health'],
['Halfords',                                    '-', '-', 'kids'],
['Betty Lewis',                                    '-', '-', 'kids'],    
['Hobbycraft Group L TUNBRIDGE WEL',            '-', 'crafts', 'kids'],
['jojo maman bebe',            '-', 'crafts', 'kids'],
['Clarks shop',            '-', 'crafts', 'kids'],
['Early learning',            '-', 'crafts', 'kids'],    
    
['Homebase Ltd 072 AYLESFORD',                  '-', 'diy', 'house'],
['Humphreys of Kings Hill WEST MALLING',        'fish chips', '-', 'entertainment'],
['Interest Charge',                             '-', 'bankcharges', 'bankcharge'],
['Interest On',                             '-', 'bankcharges', 'bankcharge'],
['Late Payment',                             '-', 'bankcharges', 'bankcharge'],
['MERCHANDISE INTEREST',                             '-', 'bankcharges', 'bankcharge'],    
['Over Credit',                             '-', 'bankcharges', 'bankcharge'],    
['JJB Sports',                                  '-', '-', 'clothes'],
['John Lewis',                                  '-', '-', 'clothes'],
['K J Edwards TONBRIDGE',                       '-', '-', 'clothes'],
['Kent Life MAIDSTONE',                         'days out', 'daysout', 'entertainment'],
['Kings Hill Opticians Ltd',                    '-', 'opticians', 'health'],
['Learning Curve GALSAHIELS',                   'toys', '-', 'kids'],
['London & South Eas WEST MALLING',             '-', 'train', 'travel'],
['London 2012',                                 'olympics', 'daysout', 'entertainment'],
['Lovely Takeaway WEST MALLING',                'eat out', 'eat out', 'entertainment'],
['MACQUARIE STORAGE LUXCO 1 SARL',              '-', '-', 'unknown'],
['MRH Offham WEST MALLING',                     'eat out', 'eat out', 'entertainment'],
['McDonalds Rest',                              'eat out', 'eat out', 'entertainment'],
['Menkind Stores Ltd STREET',                   'gifts', '-', 'gifts'],
['Mexxa Mexxa MAIDSTONE 1',                     '-', '-', 'clothes'],
['Monkey World WAREHAM',                        '-', 'daysout', 'entertainment'],
['Next 0209 Bluewater GREENHITHE',              '-', '-', 'clothes'],
['Next 0728 Staines STAINES',                   '-', '-', 'clothes'],
['Old Rectory LEYBOURNE',                       '-', '-', '-'],
['Paid item fee',                               '-', '-', 'bankcharge'],
['Pets At Home Ltd MAIDSTONE',                  'pets', '-', 'pets'],
['Phase Eight WEBSTORE UK',                     '-', '-', 'clothes'],
['Pizza Express',                               'eat out', 'eat out', 'entertainment'],
['Post and Packing KINGS HILL',                 'ebay', '-', 'ebay'],
['Pret A Manger UNIT 7,15 FRE',                 'eat out', 'eat out', 'entertainment'],
['Returned direct debit',                       'bank charges', '-', 'bankcharge'],
['SELECT CREDIT CARD',                          'bank charges', '-', 'bankcharge'],
['Shell Ham Hill SNODLAND',                     'fuel', 'car', 'travel'],
['Somerstown Coffee Hous LONDON',               'meeting', '-', 'expenses'],
['Spellbrook Leisure Ltd WALTHAM ABBEY',        'nazeing golf club', '-', 'eat out'],
['Spitfire WEST MALLING',                       'spitfire', '-', 'eat out'],
['Starbucks STAINES',                           'coffee', '-', 'luxury'],
['TFL CC/Lez Penalty 0333 200 1000',            'parkingfine', '-', 'car'],
['Texaco Broadwey Mo DORCHESTER',               'fuel', '-', 'car'],
['The King Harolds Head WALTHAM ABBEY',         'dad lunch', '-', 'eat out'],
['Ticketweb.Co.UK LONDON',                      '-', '-', 'entertainment'],
['Unauth Overdraft Fee',                        'bank charges', '-', 'bankcharge'],
['Unpaid Direct Debit Fee',                     'bank charges', '-', 'bankcharge'],
['Villa Holidays MAIDSTONE',                    'unknown', '-', 'unknown'],
['WWW.Carseatsandpushcha 07812437959',          'car', 'car', 'car'],
['WWW.Dominos.Co.UK 01908 580000',              'eat out', 'eat out', 'entertainment'],
['WWW.Dvla.Gov.UK VEHICLE LICEN',               'car', '-', 'car'],
['WWW.Nda.Ac.UK NOTTINGHAM',                    'annauni', '-', 'education'],
['WWW.Paultonspark.Co.UK ROMSEY',               'peppapig', 'daysout', 'entertainment'],
['alexander house crawley',                     'spa', 'daysout', 'entertainment'],
['rowhill reservations',                     'spa', 'daysout', 'entertainment'],    
['summer lodge',                     'spa', 'daysout', 'entertainment'],    

['phase eight',                     '-', '-', 'clothes'],
['next directory',                     '-', '-', 'clothes'],    
['sweaty betty',                     '-', '-', 'clothes'],
['Peller GREENHITHE',                     '-', '-', 'clothes'],
['mintvelvet',                     '-', '-', 'clothes'],
['monsoon',                     '-', '-', 'clothes'],
['gap',                     '-', '-', 'clothes'],
['superdry',                     '-', '-', 'clothes'],
['fatface',                     '-', '-', 'clothes'],
['topshop',                     '-', '-', 'clothes'],                    


['WWW.Preciouslittleone. INTERNET',             'car', 'car', 'car'],
['WWW.Tickets.LONDON2012 LONDON  WC2H',         'olympics', 'daysout', 'entertainment'],
['ROyal Albert Hall',         'GaryBarlow', 'daysout', 'entertainment'],    
['West Malling Flowers WEST MALLING',           'flowers', '-', 'entertainment'],

['Ikea',           'furniture', 'furniture', 'house'],
['White Company',           'furniture', 'furniture', 'house'],
['Dunelm',           'furniture', 'furniture', 'house'],        
['Sewing Room',           'furniture', 'furniture', 'house'],
['Laura Ashley',           'furniture', 'furniture', 'house'],
['Currys',           'TV', 'furniture', 'house'],
['House of Fraser',           '-', 'furniture', 'house'],    

['Ticketline',           '-', '-', 'entertainment'],
['Camping International',                       'CampingGear', 'Camping', 'house'],

    ['Alexander House',                       '', '', 'entertainment']



    
]

for tpl in _matchers:
    
    rowtmpl = "['%(phrase)s',\t\t\t'%(cty_high)s','%(cty_low)s',\t\t\t'-'],"
    d = {'phrase':tmpl[0],
         'cty_high':tmpl[3],
         'cty_low':tmpl[1]}
    print rowtmpl % d
    